version: '2'

services:

  dispatcher:
    image: nginx
    restart: always
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl
      - app-storage:/upload
    networks:
      - front-tire
    environment:
      API_SERVER_PORT: 3000
      API_SERVER_HOST: api-server
    depends_on:
      - api-server

volumes:
  app-storage:

networks:
  front-tire:
  back-tire:
